# Github action to build Docker image from main branch (tag: latest)

name: Build Docker image from main

on:
  push:
    branches:
      - main

jobs:
  bulid:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: ["arm32v7", "arm64v8", "amd64"]
        nodejs: ["node12", "node14"]
    steps:
      - name: Checkout (main)
        uses: actions/checkout@v2.3.4
        with:
          repository: 'dontobi/ioBroker.docker'
          ref: 'main'

      - name: Get and write version
        id: version
        run: |
          echo ::set-output name=version::$(cat .VERSION)
          if [[ ${{ matrix.arch }} == arm32v7 ]]; then
            echo ::set-output name=plattform::linux/arm/v7
          elif [[ ${{ matrix.arch }} == arm64v8 ]]; then
            echo ::set-output name=plattform::linux/arm64
          elif [[ ${{ matrix.arch }} == amd64 ]]; then
            echo ::set-output name=plattform::linux/amd64
          fi

      - name: Set up manifest tool
        run: |
          wget https://github.com/estesp/manifest-tool/releases/download/v1.0.3/manifest-tool-linux-amd64 -O manifest-tool
          chmod +x manifest-tool

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1.2.0

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1.5.1

      - name: Login to DockerHub
        uses: docker/login-action@v1.10.0
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: Build Docker image
        uses: docker/build-push-action@v2.7.0
        with:
          context: ./${{ matrix.nodejs }}/
          file: ./${{ matrix.nodejs }}/Dockerfile.${{ matrix.arch }}
          push: true
          platforms: ${{ steps.prep.outputs.plattform }}
          tags: |
            dontobi/iobroker.docker:${{ steps.prep.outputs.version }}-${{ matrix.nodejs }}-${{ matrix.arch }},
            dontobi/iobroker.docker:${{ steps.prep.outputs.version }}-${{ matrix.nodejs }}

        env:
          OWNER: dontobi
          PACKAGE_NAME: iobroker.docker
          PER_PAGE: 100
