# Github action to build Docker image from main branch (tag: latest)

name: Build Docker image from main

on:
  push:
    branches:
      - main

jobs:
  bulid:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: ["arm32v7", "arm64v8", "amd64"]
        nodejs: ["node12", "node14"]
    steps:
      - name: Checkout (main)
        uses: actions/checkout@v2.3.4
        with:
          repository: 'dontobi/ioBroker.docker'
          ref: 'main'

      - name: Get and write version
        id: version
        run: |
          VERSION="$(cat .VERSION)"
          echo "This is the Version: $VERSION"
          echo "version=$VERSION" >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1.2.0

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1.5.1

      - name: Login to DockerHub
        uses: docker/login-action@v1.10.0
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: Build Docker image
        uses: docker/build-push-action@v2.7.0
        with:
          context: ./${{ matrix.nodejs }}
          file: ./${{ matrix.nodejs }}/Dockerfile.${{ matrix.arch }}
          push: true
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          tags: |
            dontobi/iobroker.docker:${{ env.version }}-${{ matrix.nodejs }},
            dontobi/iobroker.docker:latest-${{ matrix.nodejs }}

        env:
          OWNER: dontobi
          PACKAGE_NAME: iobroker.docker
          PER_PAGE: 100
