# Github action to build Docker image from main branch (tag: latest)

name: Build Docker image from main

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (main)
        uses: actions/checkout@v2.3.4
        with:
          repository: 'dontobi/ioBroker.docker'
          ref: 'main'

      - name: Get and write version
        id: version
        run: |
          VERSION="$(cat .VERSION)"
          echo "version=$VERSION" >> $GITHUB_ENV

      - name: Set up manifest tool
        run: |
          wget https://github.com/estesp/manifest-tool/releases/download/v1.0.3/manifest-tool-linux-amd64 -O manifest-tool
          chmod +x manifest-tool

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1.2.0

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1.5.1

      - name: Login to DockerHub
        uses: docker/login-action@v1.10.0
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: Build Docker image (node12-amd64)
        uses: docker/build-push-action@v2.7.0
        with:
          context: ./node12
          file: ./node12/Dockerfile.amd64
          push: true
          platforms: linux/amd64
          tags: dontobi/iobroker.docker:${{ env.version }}-node12-amd64

      - name: Build Docker image (node12-arm32v7)
        uses: docker/build-push-action@v2.7.0
        with:
          context: ./node12
          file: ./node12/Dockerfile.arm32v7
          push: true
          platforms: linux/arm/v7
          tags: dontobi/iobroker.docker:${{ env.version }}-node12-arm32v7

      - name: Build Docker image (node12-arm64v8)
        uses: docker/build-push-action@v2.7.0
        with:
          context: ./node12
          file: ./node12/Dockerfile.arm64v8
          push: true
          platforms: linux/arm64
          tags: dontobi/iobroker.docker:${{ env.version }}-node12-arm64v8

      - name: Build Docker image (node14-amd64)
        uses: docker/build-push-action@v2.7.0
        with:
          context: ./node14
          file: ./node14/Dockerfile.amd64
          push: true
          platforms: linux/amd64
          tags: dontobi/iobroker.docker:${{ env.version }}-node14-amd64

      - name: Build Docker image (node14-arm32v7)
        uses: docker/build-push-action@v2.7.0
        with:
          context: ./node14
          file: ./node14/Dockerfile.arm32v7
          push: true
          platforms: linux/arm/v7
          tags: dontobi/iobroker.docker:${{ env.version }}-node14-arm32v7

      - name: Build Docker image (node14-arm64v8)
        uses: docker/build-push-action@v2.7.0
        with:
          context: ./node14
          file: ./node14/Dockerfile.arm64v8
          push: true
          platforms: linux/arm64
          tags: dontobi/iobroker.docker:${{ env.version }}-node14-arm64v8

      - name: Create and push manifests
        run: |
          sed -e "s/\${VERSION}/${{ env.version }}/g" -e "s/\${NODEJS}/node12/g" -e "s/\${DOCKERTAG}/latest-node12/g" ./manifest.yml > manifest_latest_node12.yaml
          ./manifest-tool --username ${{ secrets.DOCKER_USER }} --password ${{ secrets.DOCKER_PASS }} push from-spec manifest_latest_node12.yaml
          sed -e "s/\${VERSION}/${{ env.version }}/g" -e "s/\${NODEJS}/node14/g" -e "s/\${DOCKERTAG}/latest-node14/g" ./manifest.yml > manifest_latest_node14.yaml
          ./manifest-tool --username ${{ secrets.DOCKER_USER }} --password ${{ secrets.DOCKER_PASS }} push from-spec manifest_latest_node14.yaml
          sed -e "s/\${VERSION}/${{ env.version }}/g" -e "s/\${NODEJS}/node12/g" -e "s/\${DOCKERTAG}/${{ env.version }}-node12/g" ./manifest.yml > manifest_version_node12.yaml
          ./manifest-tool --username ${{ secrets.DOCKER_USER }} --password ${{ secrets.DOCKER_PASS }} push from-spec manifest_version_node12.yaml
          sed -e "s/\${VERSION}/${{ env.version }}/g" -e "s/\${NODEJS}/node14/g" -e "s/\${DOCKERTAG}/${{ env.version }}-node14/g" ./manifest.yml > manifest_version_node14.yaml
          ./manifest-tool --username ${{ secrets.DOCKER_USER }} --password ${{ secrets.DOCKER_PASS }} push from-spec manifest_version_node14.yaml
          sed -e "s/\${VERSION}/${{ env.version }}/g" -e "s/\${NODEJS}/node12/g" -e "s/\${DOCKERTAG}/latest/g" ./manifest.yml > manifest_latest.yaml
          ./manifest-tool --username ${{ secrets.DOCKER_USER }} --password ${{ secrets.DOCKER_PASS }} push from-spec manifest_latest.yaml
